<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="THE_EXPANDABLES" ignored="0" name="Test" tests="5" failures="1" timestamp="03 Mar 2021 15:52:53 GMT" time="0.076" errors="0">
  <testcase name="Test1" time="0.014" classname="com.wallethub.ChkRetryLogic">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase name="Test1" time="0.002" classname="com.wallethub.ChkRetryLogic">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase name="Test1" time="0.003" classname="com.wallethub.ChkRetryLogic">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase name="Test1" time="0.002" classname="com.wallethub.ChkRetryLogic">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.wallethub.ChkRetryLogic.Test1(ChkRetryLogic.java:13)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- Test1 -->
  <testcase name="Test2" time="0.002" classname="com.wallethub.ChkRetryLogic"/>
</testsuite> <!-- Test -->
